apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rws.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rws.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rws.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rws.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: COIN_MARKET_CAP_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "rws.fullname" . }}-secrets
              key: coin-market-cap-key
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
