apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rws.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rws.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ include "rws.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: coin-market-cap-key
    remoteRef:
      key: {{ .Values.externalSecrets.parameterPaths.coinMarketCapKey }}
